

%初始化编辑Matlab图形界面
figure;
syms aa1 bb3;
a=0;%相机标定图
I1=0;%二值化图片
a1=0;%横向剪切图片
hang=0;% 横向剪切图片的行扫描图
sbr='none';%相机比例字符串
set(gcf,'unit','centimeters','position',[0.1,0.2,25,12]);%设置图形区的尺寸
set(gcf,'defaultuicontrolunits','normalized')%设置用户默认空间单位属性值
h=subplot(2,2,1),imshow(a),title('相机标定图');
set(h,'position',[-0.1,0.52,0.4,0.4])
h1=subplot(2,2,2),imshow(I1),title('二值化图');
set(h1,'position',[0.25,0.6,0.2,0.2])
h2=subplot(2,2,3),imshow(a1),title('横向剪切图像');
set(h2,'position',[-0.1,0.02,0.4,0.4]);
h3=subplot(2,2,4),imshow(hang),title('扫描图');
set(h3,'position',[0.15,0.02,0.4,0.4]);
set(gcf,'defaultuicontrolhorizontal','left');
set(gcf,'defaultuicontrolfontsize',10);%设置用户默认控件字体属性值
uicontrol('style','frame',...
    'position',[0.47,0.0,0.6,1]);%设置用户控件区


%读标定图像
h_push1=uicontrol('style','push',...
   'unit','normalized','position',[0.5,0.85,0.1,0.12],...
   'string','读入标定图像','callback',[...
   '[filename,pathname]=uigetfile('' *.bmp'');'...%打开文件
   'B=strcat(pathname,filename);'...%合并字符串
   'A=imread(B);'...%读图片
   'a=A(:,:,1);'...%导出图像灰阶分布的二维数组
   'I1=0;'...
   'h=subplot(2,2,1),imshow(a),title(''相机标定图'');'...
   'set(h,''position'',[-0.1,0.5,0.4,0.4]);'...
   'h1=subplot(2,2,2),imshow(I1),title(''二值化图'');'...
   'set(h1,''position'',[0.25,0.6,0.2,0.2]);'
   ]);

%读入剪切图片
h_push2=uicontrol('style','push',...
   'unit','normalized','position',[0.7,0.85,0.15,0.12],...
   'string','读入横向剪切图像','callback',[...
   '[filename,pathname]=uigetfile('' *.bmp'');'...%打开文件
   'B1=strcat(pathname,filename);'...%合并字符串
   'A1=imread(B1);'...%读图片
   'a1=A1(:,:,1);'...%导出图像灰阶分布的二维数组
   'h2=subplot(2,2,3),imshow(a1),title(''横向剪切图像'');'...
   'set(h2,''position'',[-0.1,0.02,0.4,0.4]);'...
   'S=size(a1);'...%测量位图的尺寸
's=S(1,1)/2;'...%选择中间行
'hang=a1(s,:);'...
'h3=subplot(2,2,4),plot(hang),title(''扫描图'');'...
   'set(h3,''position'',[0.25,0.05,0.3,0.3]);'...;%画曲线
   ]);


%步骤二：标定
%对标定图片先进行二值化处理，然后找到两个点的质心并算出两个质心的距离。
%通过已知的距离数据来计算相机的比例因子
h_text=uicontrol('style','text','unit','normalized',...
    'position',[0.5,0.7,0.1,0.12],'string',{'输入标定参数 (x1,y1,x2,y2)'});
h_edit=uicontrol('style','edit','BackgroundColor','white','unit','normalized',...
    'position',[0.5,0.68,0.03,0.06],'horizontal','left',...
    'callback',[...
        'bx1=str2num(get(gcbo,''string''));']);%读入标定的第一个数值x1
 h_edit1=uicontrol('style','edit','BackgroundColor','white','unit','normalized',...
    'position',[0.53,0.68,0.03,0.06],'horizontal','left',...
    'callback',[...
        'by1=str2num(get(gcbo,''string''));']);%读入标定的第一个数值y1   
 h_edit2=uicontrol('style','edit','BackgroundColor','white','unit','normalized',...
    'position',[0.56,0.68,0.03,0.06],'horizontal','left',...
    'callback',[...
        'bx2=str2num(get(gcbo,''string''));']);%读入标定的第二个数值x2
 h_edit2=uicontrol('style','edit','BackgroundColor','white','unit','normalized',...
    'position',[0.59,0.68,0.03,0.06],'horizontal','left',...
    'callback',[...
        'by2=str2num(get(gcbo,''string''));']);%读入标定的第二个数值y2 
 h_text1=uicontrol('style','text','unit','normalized','position',[0.5,0.45,0.15,0.12],...
      'string',{'相机标定比例',sbr});%显示相机标定比例数值 
 h_push3=uicontrol('style','push',...%计算相机比例 距离按10mm计算
   'unit','normalized','position',[0.5,0.6,0.15,0.06],...
   'string','相机标定计算','callback',[...
   'br=10/sqrt((bx1-bx2)^2+(by1-by2)^2);'...
   'sbr=num2str(br);'...
    'h_text1=uicontrol(''style'',''text'',''unit'',''normalized'',''position'',[0.5,0.45,0.15,0.12],''string'',{''相机标定比例'', sbr})'
   ]);
      
%图片二值化
I=a;%
h_text2=uicontrol('style','text','unit','normalized',...
    'position',[0.5,0.32,0.1,0.12],'string',{'输入二值化值 1-254'});
h_edit3=uicontrol('style','edit','BackgroundColor','white','unit','normalized',...%输入二值化值
    'position',[0.6,0.38,0.05,0.06],'horizontal','left',...
    'callback',[...
        'by3=str2num(get(gcbo,''string''));'...
        'I=a;'...
        'J=find(I<by3);'...%小于阈值的值设置为0
        'I(J)=0;'...
        'J=find(I>=by3);'...%大于等于阈值的值设置为255
        'I(J)=255;'
        ]);
   
h_push4=uicontrol('style','push',...%二值化图生成 
   'unit','normalized','position',[0.5,0.30,0.15,0.06],...
   'string','生成二值化图','callback',[...
   'h=subplot(2,2,1),imshow(a),title(''相机标定图'');'...
   'set(h,''position'',[-0.1,0.5,0.4,0.4]);'...
   '[i,j]=find(I==255);'...%找到光斑的边缘
'm1=min(i);'...%找行的边界
'm2=max(i);'...
'n1=min(j);'...%找列的边界
'n2=max(j);'...
'mmid=round((m1+m2)/2);'...%将图形分割
'nmid=round((n1+n2)/2);'...
'I1=I(m1:m2,n1:n2);'...
'I2=im2double(I);'...%把位图数字转化为双精度值
   'h1=subplot(2,2,2),imshow(I1),title(''二值化图'');'...
   'set(h1,''position'',[0.25,0.6,0.2,0.2]);'  
]);

%横向剪切量的计算
h_push5=uicontrol('style','push',...%计算横向剪切量 
   'unit','normalized','position',[0.5,0.22,0.15,0.06],...
   'string','计算横向剪切量','callback',[...
   'XY1=zhixin(m1,mmid,n1,nmid,I2);'...%左侧图形的质心x1,y1
'XY2=zhixin(mmid,m2,nmid,n2,I2);'...%右侧图形的质心x2,y2
'ss=br*sqrt((XY1(1,1)-XY2(1,1))^2+(XY1(1,2)-XY2(1,2))^2);'...%横向剪切量
'ss1=num2str(ss);'...
'h_text3=uicontrol(''style'',''text'',''unit'',''normalized'',''position'',[0.5,0.1,0.15,0.12],''string'',{''横向剪切量'', ss1})'
  ]); 

%a1和b3的计算
h_text4=uicontrol('style','text','unit','normalized',...
    'position',[0.7,0.7,0.5,0.12],'string',{'输入横向剪切图的暗条纹x坐标, -3,-2,-1,1,2,3'});
h_edit4=uicontrol('style','edit','BackgroundColor','white','unit','normalized',...
    'position',[0.7,0.68,0.03,0.06],'horizontal','left',...
    'callback',[...
        'bt1=str2num(get(gcbo,''string''));']);%读入-3条纹
 h_edit4=uicontrol('style','edit','BackgroundColor','white','unit','normalized',...
    'position',[0.73,0.68,0.03,0.06],'horizontal','left',...
    'callback',[...
        'bt2=str2num(get(gcbo,''string''));']);%读入-2条纹  
 h_edit6=uicontrol('style','edit','BackgroundColor','white','unit','normalized',...
    'position',[0.76,0.68,0.03,0.06],'horizontal','left',...
    'callback',[...
        'bt3=str2num(get(gcbo,''string''));']);%读入-1条纹
 h_edit7=uicontrol('style','edit','BackgroundColor','white','unit','normalized',...
    'position',[0.79,0.68,0.03,0.06],'horizontal','left',...
    'callback',[...
        'bt4=str2num(get(gcbo,''string''));']);%读入1条纹 
h_edit8=uicontrol('style','edit','BackgroundColor','white','unit','normalized',...
    'position',[0.82,0.68,0.03,0.06],'horizontal','left',...
    'callback',[...
        'bt5=str2num(get(gcbo,''string''));']);%读入2条纹 
h_edit9=uicontrol('style','edit','BackgroundColor','white','unit','normalized',...
    'position',[0.85,0.68,0.03,0.06],'horizontal','left',...
    'callback',[...
        'bt6=str2num(get(gcbo,''string''));']);%读入3条纹 
 
  h_push6=uicontrol('style','push',...%计算a1和b3参数
   'unit','normalized','position',[0.7,0.6,0.15,0.06],...
   'string','a1 和b3 参数','callback',[... 
  'lambda=0.0006328;'...
't=(bt6-bt1)/2+bt1;'...
  't1=(bt1-t)*br;'...
't2=(bt2-t)*br;'...
't3=(bt3-t)*br;'...
't4=(bt4-t)*br;'...
't5=(bt5-t)*br;'...
't6=(bt6-t)*br;'...%不同孔径下的值 
'eq1=2*t1*ss*aa1+4*ss*bb3*t1^3+bb3*t1*ss^3-0.5*(-3)*lambda;'...
'eq2=2*t3*ss*aa1+4*ss*bb3*t3^3+bb3*t3*ss^3-0.5*(-1)*lambda;'...
'[aa1,bb3]=solve(eq1,eq2);'...
'aa1=double(aa1);'...
'bb3=double(bb3);'...
'aaa1=num2str(aa1);'...
'bbb3=num2str(bb3);'...
'h_text5=uicontrol(''style'',''text'',''unit'',''normalized'',''position'',[0.85,0.45,0.10,0.2],''string'',{''a1='', aaa1,''b3='',bbb3})'
])
h_text6=uicontrol('style','text','unit','normalized',...
    'position',[0.7,0.3,0.5,0.12],'string',{'输入焦距坐标mm'});
h_edit10=uicontrol('style','edit','BackgroundColor','white','unit','normalized',...
    'position',[0.7,0.3,0.06,0.06],'horizontal','left',...
    'callback',[...
        'ff=str2num(get(gcbo,''string''));']);%输入焦距值 
h_text7=uicontrol('style','text','unit','normalized',...
    'position',[0.85,0.3,0.5,0.12],'string',{'输入半径值mm'});
h_edit11=uicontrol('style','edit','BackgroundColor','white','unit','normalized',...
    'position',[0.85,0.3,0.06,0.06],'horizontal','left',...
    'callback',[...
        'RR=str2num(get(gcbo,''string''));']);%输入半径值
    h_push7=uicontrol('style','push',...%计算
   'unit','normalized','position',[0.7,0.2,0.25,0.06],...
   'string','轴向离焦距离和初级球差','callback',[... 
   'deltaZ=aa1*2*ff^2;'...
   'deltaL=4*ff ^2*bb3*RR^2;'...
   'deltaZZ=num2str(deltaZ);'...
   'deltaLL=num2str(deltaL);'...
   'h_text8=uicontrol(''style'',''text'',''unit'',''normalized'',''position'',[0.7,0.05,0.5,0.15],''string'',{''deltaZ(轴向离焦距离）='', deltaZZ,''deltaL（初级球差）='',deltaLL})'
   ]);



  

   
   





       




